// This file is generated by scripts/fetch-releases.mjs.
// Do not edit it manually.

import type { MusicRelease } from "@/types/release";

export const releaseDataMetadata = {
  "targetDate": "2026-08-21",
  "generatedAt": "2026-08-20T17:08:50.851Z",
  "coverRequired": true,
  "spotifyCoverLookupEnabled": true,
  "spotifyArtistImageFallbackEnabled": true,
  "spotifyArtistImageFallbackCount": 15,
  "fetchedCount": 0,
  "curatedCount": 0,
  "redditSingleCount": 43,
  "candidateCount": 43,
  "storedReleaseCount": 0,
  "coverLookupCandidateCount": 43,
  "coverQualifiedCount": 42,
  "skippedMissingCoverCount": 1,
  "missingCovers": [
    {
      "artist": "Marlo, Mali",
      "title": "Clipchaser",
      "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/"
    }
  ],
  "fetchError": null,
  "sourceCounts": {
    "r/GermanRap + Spotify NZ": 26,
    "r/GermanRap + Spotify artist image fallback": 15,
    "r/GermanRap + Apple Music NZ": 1
  }
} as const;

export const realReleases: MusicRelease[] = [
  {
    "id": "reddit-389c54a8daba3c2d",
    "artist": "1 Tasche, JET069",
    "title": "CD's im VIP",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "1 Tasche, JET069 veröffentlicht die Single „CD's im VIP“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273177f9150cf478c0bc06dbfee",
    "spotifyUrl": "https://open.spotify.com/track/7wxAmMr94OjZ2D80Ef1p1j"
  },
  {
    "id": "reddit-513860ba885e6059",
    "artist": "Aymen",
    "title": "Drunk in Love",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Aymen veröffentlicht die Single „Drunk in Love“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273ab36843ad217c308c03c79aa",
    "spotifyUrl": "https://open.spotify.com/track/6vHCbs4JIkd9uGBRfchWDN"
  },
  {
    "id": "reddit-9896c562312bf6fa",
    "artist": "Baba F",
    "title": "Er ist da drüben",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Baba F veröffentlicht die Single „Er ist da drüben“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b27342c7f0158e5f6290f58a918d",
    "artistImageSourceUrl": "https://open.spotify.com/artist/3dRfIFn2ITahu7IN1xdcR7"
  },
  {
    "id": "reddit-7209dc6f68fb079b",
    "artist": "Blender, absent",
    "title": "Schweigepflicht",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Blender, absent veröffentlicht die Single „Schweigepflicht“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273f5a7f57c694801dc62d383a0",
    "spotifyUrl": "https://open.spotify.com/track/12Twlhs4oejhMEdQ6SGwRE"
  },
  {
    "id": "reddit-c8c8016aef722f32",
    "artist": "Bobby Vandamme",
    "title": "Brazil Funk Freestyle 3 🇧🇷",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Bobby Vandamme veröffentlicht die Single „Brazil Funk Freestyle 3 🇧🇷“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5eb1abed3cdee25ae2e6fab69d3",
    "artistImageSourceUrl": "https://open.spotify.com/artist/054k3bx4tpjx1tfypvq3eq"
  },
  {
    "id": "reddit-89321ddedfbdde89",
    "artist": "CANER, CALO",
    "title": "OMG",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "CANER, CALO veröffentlicht die Single „OMG“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2734ace13965fdf484c5944681e",
    "spotifyUrl": "https://open.spotify.com/track/1ND0x4kertYBQyITnFTNMy"
  },
  {
    "id": "reddit-0b4e16c87b5af593",
    "artist": "Capital Bra, Samra, LACAZETTE",
    "title": "Böse Jungs",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Capital Bra, Samra, LACAZETTE veröffentlicht die Single „Böse Jungs“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5ebfc9cbf00210113b93a91efd1",
    "artistImageSourceUrl": "https://open.spotify.com/artist/4WZGDpNwrC0vNQyl9QzF7d"
  },
  {
    "id": "reddit-5d8f00921589b9b3",
    "artist": "Chayn, absent",
    "title": "LAUT",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Chayn, absent veröffentlicht die Single „LAUT“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2735c57bd534ba818a30706e127",
    "spotifyUrl": "https://open.spotify.com/track/51PIoDE9jo3ZKMST3yl42y"
  },
  {
    "id": "reddit-1d7dd10bc77b9cbb",
    "artist": "Der Yavuz",
    "title": "Hustler Ambitions",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Der Yavuz veröffentlicht die Single „Hustler Ambitions“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b27331bee5af1e6e8455e0747f5e",
    "spotifyUrl": "https://open.spotify.com/track/5z1upFFqyFZ9y1pLTBXWXa"
  },
  {
    "id": "reddit-08853834116e9d7c",
    "artist": "DJ TÖRKE, FiNCH, Doktormethoden & Doktormithoden",
    "title": "50 KUBiK",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "DJ TÖRKE, FiNCH, Doktormethoden & Doktormithoden veröffentlicht die Single „50 KUBiK“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273cbd6e50a6134c074ac3b28de",
    "spotifyUrl": "https://open.spotify.com/track/50n0IAdwXx3ExIBM0R7gRB"
  },
  {
    "id": "reddit-f669cf92068ec190",
    "artist": "Elly",
    "title": "Wo bist du",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Elly veröffentlicht die Single „Wo bist du“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273c5f2f269602582f2b43aaa3b",
    "spotifyUrl": "https://open.spotify.com/track/5Il7KZKdX0saAscs0JNBJa"
  },
  {
    "id": "reddit-700be4af7c347db2",
    "artist": "Fa",
    "title": "17 Uhr",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Fa veröffentlicht die Single „17 Uhr“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b27320fb042a26af7a7d333b0b15",
    "spotifyUrl": "https://open.spotify.com/track/3otFBHOkR8cAo9AId4adFS"
  },
  {
    "id": "reddit-4dbc2655371cce4f",
    "artist": "Faroon",
    "title": "ONE",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Faroon veröffentlicht die Single „ONE“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5eb172705a4b66cac65102092c1",
    "artistImageSourceUrl": "https://open.spotify.com/artist/697ZbUKLJSEWWhtayAGxBY"
  },
  {
    "id": "reddit-6cf299c61064f618",
    "artist": "FAYAN",
    "title": "LÄCHELN IM GESICHT",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "FAYAN veröffentlicht die Single „LÄCHELN IM GESICHT“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Apple Music NZ",
    "coverUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/7a/9b/0a/7a9b0af0-d5e2-9d5d-30df-09cb0c96e40f/8718521104177.jpg/1200x1200bb.jpg",
    "appleMusicUrl": "https://music.apple.com/nz/album/l%C3%A4cheln-im-gesicht/6789563737?i=6789563751&uo=4",
    "trackCount": 1
  },
  {
    "id": "reddit-2c97323e1b0cff47",
    "artist": "Gangsta Ralph",
    "title": "Plötzlich",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Gangsta Ralph veröffentlicht die Single „Plötzlich“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5ebbb4f3d89d29681085845654a",
    "artistImageSourceUrl": "https://open.spotify.com/artist/2N3l2KHvPvRPi4qFFoVZuU"
  },
  {
    "id": "reddit-b1cee196f019d1ff",
    "artist": "Hemso, GAMBINO 36",
    "title": "Auf den Strassen",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Hemso, GAMBINO 36 veröffentlicht die Single „Auf den Strassen“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2732c2741070e60252847c7aae1",
    "spotifyUrl": "https://open.spotify.com/track/1nPWUXGHFH0FPzxMZ3l9Lw"
  },
  {
    "id": "reddit-ffd5d4958b05b697",
    "artist": "Hoti",
    "title": "Kopfsache",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Hoti veröffentlicht die Single „Kopfsache“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5ebcea7310f46f6529f1fd6c43c",
    "artistImageSourceUrl": "https://open.spotify.com/artist/3JjV29S3jjRRqt82qdqVJC"
  },
  {
    "id": "reddit-5df48c847e46fe0e",
    "artist": "IMMI",
    "title": "Oranienplatz",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "IMMI veröffentlicht die Single „Oranienplatz“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2733182ad6dc87d9ae8a75ffc57",
    "spotifyUrl": "https://open.spotify.com/track/1h93DSP4YsNq2RxLVrqpX0"
  },
  {
    "id": "reddit-8283ad01a504dc24",
    "artist": "Jean, Solé",
    "title": "KANKA",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Jean, Solé veröffentlicht die Single „KANKA“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2732da280521b0c0ecbe8a30127",
    "spotifyUrl": "https://open.spotify.com/track/734yUviYuPyjIPhjXjZNxw"
  },
  {
    "id": "reddit-1a85a0566efef792",
    "artist": "KARDO, X Wave",
    "title": "BABY BOY (2026)",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "KARDO, X Wave veröffentlicht die Single „BABY BOY (2026)“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5eb2a66d8e74b27d014061dd5cb",
    "artistImageSourceUrl": "https://open.spotify.com/artist/3NZPZUWDcJngcu8MuBpT69"
  },
  {
    "id": "reddit-e5e14513934ff05a",
    "artist": "Koushino",
    "title": "Ich denk",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Koushino veröffentlicht die Single „Ich denk“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5eb50639fa73d331fd7624b5353",
    "artistImageSourceUrl": "https://open.spotify.com/artist/6TR6dUNDpqyitYzDvY7DI0"
  },
  {
    "id": "reddit-89634fe278f13af8",
    "artist": "Layn",
    "title": "Besser zu zweit",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Layn veröffentlicht die Single „Besser zu zweit“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273612ff1ab435574c617600958",
    "spotifyUrl": "https://open.spotify.com/track/0bxFv4tnEDkE4A18EkW4ls"
  },
  {
    "id": "reddit-9e146506822776a3",
    "artist": "LX, Maxwell",
    "title": "JUMP'N RUN",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "LX, Maxwell veröffentlicht die Single „JUMP'N RUN“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5eb982be803076749939374ae64",
    "artistImageSourceUrl": "https://open.spotify.com/artist/10XY9PZCJKzUFzZOdtlQLU"
  },
  {
    "id": "reddit-ce46063d5fe287bd",
    "artist": "makko, The Chainsmokers",
    "title": "Inundauswendig",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "makko, The Chainsmokers veröffentlicht die Single „Inundauswendig“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273bd9982d65b699012379d87ce",
    "spotifyUrl": "https://open.spotify.com/track/1DOVkuzAdnyHgDJXbp92Wq"
  },
  {
    "id": "reddit-478ebba989908569",
    "artist": "Marteria, luzey",
    "title": "Endlich Normale Träume",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Marteria, luzey veröffentlicht die Single „Endlich Normale Träume“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2739f904e4c861e406df1f411be",
    "spotifyUrl": "https://open.spotify.com/track/5tI29X3CK0J4qF65vLORQq"
  },
  {
    "id": "reddit-32965628024dbc9b",
    "artist": "Milli, boundrxy",
    "title": "COD",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Milli, boundrxy veröffentlicht die Single „COD“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2736b5e398fcd1c2dc1eaccddbd",
    "spotifyUrl": "https://open.spotify.com/track/1O3Q2O4PF4lHIH8e4X3GFA"
  },
  {
    "id": "reddit-70cae7bc68f8475c",
    "artist": "Milonair",
    "title": "Drogenmusik",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Milonair veröffentlicht die Single „Drogenmusik“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5ebd18ba298d05c5b0d0516b306",
    "artistImageSourceUrl": "https://open.spotify.com/artist/6AZfDB8isLU2sHkSm3sRhX"
  },
  {
    "id": "reddit-9242f50349f57068",
    "artist": "MiZeb",
    "title": "Abrechnung",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "MiZeb veröffentlicht die Single „Abrechnung“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273da962926e3e56ba2afdd7614",
    "spotifyUrl": "https://open.spotify.com/track/1M9YX8DZldKEZ6nV6684in"
  },
  {
    "id": "reddit-0f739982066df952",
    "artist": "PA Sports, Mucco",
    "title": "Dubai",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "PA Sports, Mucco veröffentlicht die Single „Dubai“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5ebafe12346e8683f11e5722acb",
    "artistImageSourceUrl": "https://open.spotify.com/artist/2qMezKrAKRh2Z2uR3fCqHt"
  },
  {
    "id": "reddit-c57870715a28ab3b",
    "artist": "Pajel",
    "title": "4YOU / TRENDZ",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Pajel veröffentlicht die Single „4YOU / TRENDZ“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5eb60d421cdfdbc1dbdb616ee06",
    "artistImageSourceUrl": "https://open.spotify.com/artist/1bpI6QDUqmfKmV0Tlhj0Jm"
  },
  {
    "id": "reddit-5d6bbdb408e03196",
    "artist": "Paul, 01099",
    "title": "Wo ist der DJ",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Paul, 01099 veröffentlicht die Single „Wo ist der DJ“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2731c04a2e43618526e216e3c3e",
    "spotifyUrl": "https://open.spotify.com/track/6GagT50zogqk5qzAPT6nVw"
  },
  {
    "id": "reddit-398f4c056060216b",
    "artist": "RAPK",
    "title": "Dalmatiner",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "RAPK veröffentlicht die Single „Dalmatiner“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2737e205615e34e9fcc6cabeabe",
    "spotifyUrl": "https://open.spotify.com/track/2NF4OSSSL5zfvladb185Y9"
  },
  {
    "id": "reddit-1fc47058b7ee71a4",
    "artist": "Rubi",
    "title": "2MG",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Rubi veröffentlicht die Single „2MG“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273971610f96f91b4004bce1566",
    "spotifyUrl": "https://open.spotify.com/track/3fIY3qPEfdvUiD35HPbOtq"
  },
  {
    "id": "reddit-0a69262a6670fdc6",
    "artist": "Sero El Mero",
    "title": "Güzelim",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Sero El Mero veröffentlicht die Single „Güzelim“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273c494e5566ab2e40cee86efd7",
    "spotifyUrl": "https://open.spotify.com/track/0uJDlEQq0l18fXbavoWPB9"
  },
  {
    "id": "reddit-f0350423222bfec4",
    "artist": "Sharaktah",
    "title": "VERMISS MICH",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Sharaktah veröffentlicht die Single „VERMISS MICH“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273ede44ef81dcf66fd86a00882",
    "spotifyUrl": "https://open.spotify.com/track/3v0VIKNvSEvShiN6fpd3YO"
  },
  {
    "id": "reddit-cc5c0d099a28c83f",
    "artist": "Sido",
    "title": "ISSA",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Sido veröffentlicht die Single „ISSA“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5eb63efaf5ffb7ecc44e25a72cf",
    "artistImageSourceUrl": "https://open.spotify.com/artist/4Yttlv9ndGjCDCVLqM7ACq"
  },
  {
    "id": "reddit-4d873b27b299ac7d",
    "artist": "SIL3A",
    "title": "Gangsters Fi Marbella",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "SIL3A veröffentlicht die Single „Gangsters Fi Marbella“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2739a56e9d137939235430ea179",
    "spotifyUrl": "https://open.spotify.com/track/4YWsyT0JLQOM8QsVXTLdzb"
  },
  {
    "id": "reddit-c18f5ce199eee712",
    "artist": "Undacava, Lyrica030",
    "title": "A.B.S (Nachts im Tunnel)",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Undacava, Lyrica030 veröffentlicht die Single „A.B.S (Nachts im Tunnel)“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5eba255725c8d5a046682b5cf4c",
    "artistImageSourceUrl": "https://open.spotify.com/artist/0GICHCgSgJrRnanaNRFIMX"
  },
  {
    "id": "reddit-109c342621759af7",
    "artist": "Verifiziert",
    "title": "vvm",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Verifiziert veröffentlicht die Single „vvm“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify artist image fallback",
    "coverUrl": "https://i.scdn.co/image/ab6761610000e5ebf898fb8510da1c57bc2f2baf",
    "artistImageSourceUrl": "https://open.spotify.com/artist/1SF4jakSq8kI38MYjFdaJG"
  },
  {
    "id": "reddit-15666079a7d532bc",
    "artist": "Vetlaney",
    "title": "Märchenprinz",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Vetlaney veröffentlicht die Single „Märchenprinz“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b27388af9c1fe072edfc8cfcee4c",
    "spotifyUrl": "https://open.spotify.com/track/2slcMoVNhcLNgV97kuhqjs"
  },
  {
    "id": "reddit-598e05fc7e662155",
    "artist": "YENVI",
    "title": "TEST",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "YENVI veröffentlicht die Single „TEST“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b27323a61be30d0e048f46203009",
    "spotifyUrl": "https://open.spotify.com/track/4ae7Cl6HR4399LBTeH9Cut"
  },
  {
    "id": "reddit-2e4dccb59c5577be",
    "artist": "Zate",
    "title": "Letzter Bus",
    "releaseDate": "2026-08-21",
    "country": "DE",
    "kind": "single",
    "sourceUrl": "https://www.reddit.com/r/GermanRap/comments/1vtn3kv/die_releases_am_21082026/",
    "description": "Zate veröffentlicht die Single „Letzter Bus“.",
    "genres": [
      "Deutschrap",
      "Hip-Hop/Rap"
    ],
    "source": "r/GermanRap + Spotify NZ",
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2732c24319bffb1f71e275d3644",
    "spotifyUrl": "https://open.spotify.com/track/0LGQtfnQASSKn9OaZ0RTUj"
  }
];
