create or replace function private.release_identity_key(
  p_release_date date,
  p_artist text,
  p_title text
)
returns text
language sql
immutable
set search_path = ''
as $$
  select to_char(p_release_date, 'YYYY-MM-DD')
    || '|'
    || regexp_replace(
      translate(
        replace(
          regexp_replace(lower(btrim(coalesce(p_artist, ''))), '\s+(feat\.?|ft\.?|featuring|with|x|&|\+)\s+', '&', 'gi'),
          'ß',
          'ss'
        ),
        'äöüáàâãåéèêëíìîïóòôõúùûçñýÿ',
        'aouaaaaaeeeeiiiioooouuucnyy'
      ),
      '[^a-z0-9]+',
      '',
      'g'
    )
    || '|'
    || regexp_replace(
      translate(
        replace(lower(btrim(coalesce(p_title, ''))), 'ß', 'ss'),
        'äöüáàâãåéèêëíìîïóòôõúùûçñýÿ',
        'aouaaaaaeeeeiiiioooouuucnyy'
      ),
      '[^a-z0-9]+',
      '',
      'g'
    );
$$;

revoke all on function private.release_identity_key(date, text, text) from public, anon, authenticated;
grant usage on schema private to authenticated, service_role;
grant execute on function private.release_identity_key(date, text, text) to authenticated, service_role;

alter table public.releases
  add column if not exists identity_key text
  generated always as (private.release_identity_key(release_date, artist, title)) stored;

create unique index if not exists releases_identity_key_unique_idx
  on public.releases (identity_key);

create table if not exists public.release_import_runs (
  id uuid primary key default gen_random_uuid(),
  target_date date not null,
  region_scope text not null default 'ALL' check (region_scope in ('ALL', 'DE', 'US')),
  source text not null default 'multi_source_research',
  status text not null default 'collecting'
    check (status in ('collecting', 'review', 'processing', 'completed', 'failed', 'rolled_back')),
  stats jsonb not null default '{}'::jsonb check (jsonb_typeof(stats) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz null
);

create unique index if not exists release_import_runs_active_unique_idx
  on public.release_import_runs (target_date, region_scope)
  where status in ('collecting', 'review', 'processing');

create index if not exists release_import_runs_target_date_idx
  on public.release_import_runs (target_date desc, created_at desc);

create table if not exists public.release_candidates (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.release_import_runs(id) on delete cascade,
  artist text not null check (char_length(btrim(artist)) between 1 and 200),
  title text not null check (char_length(btrim(title)) between 1 and 240),
  release_date date not null,
  country text not null check (country in ('DE', 'US')),
  kind text not null check (kind in ('album', 'ep', 'single', 'mixtape')),
  track_count smallint null check (track_count is null or track_count between 1 and 999),
  description text null check (description is null or char_length(description) <= 5000),
  genres text[] not null default '{}',
  spotify_url text null,
  spotify_pre_save_url text null,
  apple_music_url text null,
  youtube_url text null,
  source_url text null,
  cover_url text null,
  storage_path text null,
  cover_kind text not null default 'missing'
    check (cover_kind in ('official', 'artist_fallback', 'missing')),
  primary_source text not null,
  sources jsonb not null default '[]'::jsonb check (jsonb_typeof(sources) = 'array'),
  confidence text not null default 'likely'
    check (confidence in ('uncertain', 'likely', 'confirmed')),
  warning_codes text[] not null default '{}',
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'duplicate')),
  matched_release_id uuid null references public.releases(id) on delete set null,
  identity_key text
    generated always as (private.release_identity_key(release_date, artist, title)) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists release_candidates_run_identity_unique_idx
  on public.release_candidates (run_id, identity_key);

create index if not exists release_candidates_review_idx
  on public.release_candidates (run_id, status, country, kind);

create table if not exists public.release_import_changes (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.release_import_runs(id) on delete cascade,
  candidate_id uuid null references public.release_candidates(id) on delete set null,
  release_id uuid null references public.releases(id) on delete set null,
  release_identity_key text not null,
  action text not null check (action in ('inserted', 'updated')),
  before_snapshot jsonb null,
  after_snapshot jsonb not null,
  rollback_status text not null default 'pending'
    check (rollback_status in ('pending', 'restored', 'skipped', 'failed')),
  rollback_message text null,
  created_at timestamptz not null default now(),
  rolled_back_at timestamptz null
);

create index if not exists release_import_changes_run_idx
  on public.release_import_changes (run_id, created_at);

drop trigger if exists set_release_import_runs_updated_at on public.release_import_runs;
create trigger set_release_import_runs_updated_at
before update on public.release_import_runs
for each row execute function public.set_release_updated_at();

drop trigger if exists set_release_candidates_updated_at on public.release_candidates;
create trigger set_release_candidates_updated_at
before update on public.release_candidates
for each row execute function public.set_release_updated_at();

alter table public.release_import_runs enable row level security;
alter table public.release_candidates enable row level security;
alter table public.release_import_changes enable row level security;

grant select on public.releases to authenticated;

revoke all on public.release_import_runs from anon;
revoke all on public.release_candidates from anon;
revoke all on public.release_import_changes from anon;

grant select, insert, update, delete on public.release_import_runs to authenticated;
grant select, insert, update, delete on public.release_candidates to authenticated;
grant select, insert, update on public.release_import_changes to authenticated;
grant all on public.release_import_runs to service_role;
grant all on public.release_candidates to service_role;
grant all on public.release_import_changes to service_role;

drop policy if exists "Admins can manage release import runs" on public.release_import_runs;
create policy "Admins can manage release import runs"
on public.release_import_runs
for all
to authenticated
using (
  exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can manage release candidates" on public.release_candidates;
create policy "Admins can manage release candidates"
on public.release_candidates
for all
to authenticated
using (
  exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can read release import changes" on public.release_import_changes;
create policy "Admins can read release import changes"
on public.release_import_changes
for select
to authenticated
using (
  exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can update release import changes" on public.release_import_changes;
create policy "Admins can update release import changes"
on public.release_import_changes
for update
to authenticated
using (
  exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can create release import changes" on public.release_import_changes;
create policy "Admins can create release import changes"
on public.release_import_changes
for insert
to authenticated
with check (
  exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  )
);

create or replace function public.ingest_release_candidates(
  p_run_id uuid,
  p_candidates jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_processed integer := 0;
  v_pending integer := 0;
begin
  if jsonb_typeof(p_candidates) <> 'array' then
    raise exception 'candidates must be an array';
  end if;

  if jsonb_array_length(p_candidates) = 0 or jsonb_array_length(p_candidates) > 300 then
    raise exception 'candidates must contain between 1 and 300 items';
  end if;

  if not exists (
    select 1
    from public.release_import_runs
    where id = p_run_id
  ) then
    raise exception 'release import run not found';
  end if;

  with incoming_raw as (
    select source.ordinality, candidate.*
    from jsonb_array_elements(p_candidates) with ordinality as source(value, ordinality)
    cross join lateral jsonb_to_record(source.value) as candidate (
      artist text,
      title text,
      release_date date,
      country text,
      kind text,
      track_count smallint,
      description text,
      genres text[],
      spotify_url text,
      spotify_pre_save_url text,
      apple_music_url text,
      youtube_url text,
      source_url text,
      cover_url text,
      storage_path text,
      cover_kind text,
      primary_source text,
      sources jsonb,
      confidence text,
      warning_codes text[]
    )
  ),
  incoming as (
    select distinct on (private.release_identity_key(release_date, artist, title)) *
    from incoming_raw
    order by private.release_identity_key(release_date, artist, title), ordinality desc
  ),
  upserted as (
    insert into public.release_candidates (
      run_id,
      artist,
      title,
      release_date,
      country,
      kind,
      track_count,
      description,
      genres,
      spotify_url,
      spotify_pre_save_url,
      apple_music_url,
      youtube_url,
      source_url,
      cover_url,
      storage_path,
      cover_kind,
      primary_source,
      sources,
      confidence,
      warning_codes
    )
    select
      p_run_id,
      artist,
      title,
      release_date,
      country,
      kind,
      track_count,
      description,
      coalesce(genres, '{}'::text[]),
      spotify_url,
      spotify_pre_save_url,
      apple_music_url,
      youtube_url,
      source_url,
      cover_url,
      storage_path,
      coalesce(cover_kind, 'missing'),
      primary_source,
      coalesce(sources, '[]'::jsonb),
      coalesce(confidence, 'likely'),
      coalesce(warning_codes, '{}'::text[])
    from incoming
    on conflict (run_id, identity_key)
    do update set
      kind = excluded.kind,
      track_count = coalesce(excluded.track_count, release_candidates.track_count),
      description = coalesce(nullif(excluded.description, ''), release_candidates.description),
      genres = case
        when coalesce(array_length(excluded.genres, 1), 0) > 0 then excluded.genres
        else release_candidates.genres
      end,
      spotify_url = coalesce(nullif(excluded.spotify_url, ''), release_candidates.spotify_url),
      spotify_pre_save_url = coalesce(nullif(excluded.spotify_pre_save_url, ''), release_candidates.spotify_pre_save_url),
      apple_music_url = coalesce(nullif(excluded.apple_music_url, ''), release_candidates.apple_music_url),
      youtube_url = coalesce(nullif(excluded.youtube_url, ''), release_candidates.youtube_url),
      source_url = coalesce(nullif(excluded.source_url, ''), release_candidates.source_url),
      cover_url = coalesce(nullif(excluded.cover_url, ''), release_candidates.cover_url),
      storage_path = coalesce(nullif(excluded.storage_path, ''), release_candidates.storage_path),
      cover_kind = case
        when excluded.storage_path is not null then excluded.cover_kind
        else release_candidates.cover_kind
      end,
      primary_source = release_candidates.primary_source,
      sources = (
        select coalesce(jsonb_agg(source_item), '[]'::jsonb)
        from (
          select distinct source_item
          from jsonb_array_elements(
            coalesce(release_candidates.sources, '[]'::jsonb)
            || coalesce(excluded.sources, '[]'::jsonb)
          ) as source_item
        ) as merged_sources
      ),
      confidence = case
        when release_candidates.confidence = 'confirmed' or excluded.confidence = 'confirmed' then 'confirmed'
        when release_candidates.confidence = 'likely' or excluded.confidence = 'likely' then 'likely'
        else 'uncertain'
      end,
      warning_codes = array(
        select distinct warning
        from unnest(release_candidates.warning_codes || excluded.warning_codes) as warning
        where warning <> 'missing_stored_cover'
          or coalesce(excluded.storage_path, release_candidates.storage_path) is null
      )
    where release_candidates.status = 'pending'
    returning id
  )
  select count(*)::integer into v_processed from upserted;

  select count(*)::integer
  into v_pending
  from public.release_candidates
  where run_id = p_run_id
    and status = 'pending';

  update public.release_import_runs
  set
    status = 'review',
    completed_at = null,
    stats = jsonb_build_object(
      'pending', v_pending,
      'total', (
        select count(*)
        from public.release_candidates
        where run_id = p_run_id
      )
    )
  where id = p_run_id;

  return jsonb_build_object(
    'processed', v_processed,
    'pending', v_pending
  );
end;
$$;

revoke all on function public.ingest_release_candidates(uuid, jsonb) from public, anon, authenticated;
grant execute on function public.ingest_release_candidates(uuid, jsonb) to service_role;

create or replace function public.accept_release_candidates(
  p_run_id uuid,
  p_candidate_ids uuid[],
  p_status text default 'published'
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_candidate public.release_candidates%rowtype;
  v_existing public.releases%rowtype;
  v_after public.releases%rowtype;
  v_inserted integer := 0;
  v_updated integer := 0;
  v_skipped integer := 0;
  v_pending integer := 0;
begin
  if p_status not in ('draft', 'published') then
    raise exception 'status must be draft or published';
  end if;

  if coalesce(array_length(p_candidate_ids, 1), 0) = 0 then
    raise exception 'at least one candidate is required';
  end if;

  if not exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  ) then
    raise exception 'release admin access required';
  end if;

  perform 1
  from public.release_import_runs
  where id = p_run_id
  for update;

  if not found then
    raise exception 'release import run not found';
  end if;

  update public.release_import_runs
  set status = 'processing', completed_at = null
  where id = p_run_id;

  for v_candidate in
    select *
    from public.release_candidates
    where run_id = p_run_id
      and id = any(p_candidate_ids)
      and status = 'pending'
    order by created_at, id
    for update
  loop
    select *
    into v_existing
    from public.releases
    where identity_key = v_candidate.identity_key
    limit 1
    for update;

    if found then
      update public.releases as release
      set
        cover_url = coalesce(nullif(release.cover_url, ''), v_candidate.cover_url),
        storage_path = coalesce(nullif(release.storage_path, ''), v_candidate.storage_path),
        spotify_url = coalesce(nullif(release.spotify_url, ''), v_candidate.spotify_url),
        spotify_pre_save_url = coalesce(nullif(release.spotify_pre_save_url, ''), v_candidate.spotify_pre_save_url),
        apple_music_url = coalesce(nullif(release.apple_music_url, ''), v_candidate.apple_music_url),
        youtube_url = coalesce(nullif(release.youtube_url, ''), v_candidate.youtube_url),
        source_url = coalesce(nullif(release.source_url, ''), v_candidate.source_url),
        description = coalesce(nullif(release.description, ''), v_candidate.description),
        track_count = coalesce(release.track_count, v_candidate.track_count),
        genres = case
          when coalesce(array_length(release.genres, 1), 0) = 0 then v_candidate.genres
          else release.genres
        end,
        status = p_status
      where release.id = v_existing.id
      returning * into v_after;

      insert into public.release_import_changes (
        run_id,
        candidate_id,
        release_id,
        release_identity_key,
        action,
        before_snapshot,
        after_snapshot
      )
      values (
        p_run_id,
        v_candidate.id,
        v_after.id,
        v_candidate.identity_key,
        'updated',
        to_jsonb(v_existing),
        to_jsonb(v_after)
      );

      update public.release_candidates
      set status = 'duplicate', matched_release_id = v_after.id
      where id = v_candidate.id;

      v_updated := v_updated + 1;
      continue;
    end if;

    if p_status = 'published'
      and (v_candidate.cover_url is null or v_candidate.storage_path is null)
    then
      update public.release_candidates
      set warning_codes = array(
        select distinct code
        from unnest(warning_codes || array['missing_stored_cover']::text[]) as code
      )
      where id = v_candidate.id;
      v_skipped := v_skipped + 1;
      continue;
    end if;

    insert into public.releases (
      artist,
      title,
      release_date,
      country,
      kind,
      track_count,
      description,
      genres,
      spotify_url,
      spotify_pre_save_url,
      apple_music_url,
      youtube_url,
      source_url,
      cover_url,
      storage_path,
      source,
      status,
      created_by
    )
    values (
      v_candidate.artist,
      v_candidate.title,
      v_candidate.release_date,
      v_candidate.country,
      v_candidate.kind,
      v_candidate.track_count,
      v_candidate.description,
      v_candidate.genres,
      v_candidate.spotify_url,
      v_candidate.spotify_pre_save_url,
      v_candidate.apple_music_url,
      v_candidate.youtube_url,
      v_candidate.source_url,
      v_candidate.cover_url,
      v_candidate.storage_path,
      'Release Inbox · ' || v_candidate.primary_source,
      p_status,
      (select auth.uid())
    )
    returning * into v_after;

    insert into public.release_import_changes (
      run_id,
      candidate_id,
      release_id,
      release_identity_key,
      action,
      before_snapshot,
      after_snapshot
    )
    values (
      p_run_id,
      v_candidate.id,
      v_after.id,
      v_candidate.identity_key,
      'inserted',
      null,
      to_jsonb(v_after)
    );

    update public.release_candidates
    set status = 'accepted', matched_release_id = v_after.id
    where id = v_candidate.id;

    v_inserted := v_inserted + 1;
  end loop;

  select count(*)::integer
  into v_pending
  from public.release_candidates
  where run_id = p_run_id
    and status = 'pending';

  update public.release_import_runs
  set
    status = case when v_pending = 0 then 'completed' else 'review' end,
    completed_at = case when v_pending = 0 then now() else null end,
    stats = jsonb_build_object(
      'pending', v_pending,
      'accepted', (
        select count(*)
        from public.release_candidates
        where run_id = p_run_id and status = 'accepted'
      ),
      'duplicates', (
        select count(*)
        from public.release_candidates
        where run_id = p_run_id and status = 'duplicate'
      ),
      'rejected', (
        select count(*)
        from public.release_candidates
        where run_id = p_run_id and status = 'rejected'
      )
    )
  where id = p_run_id;

  return jsonb_build_object(
    'inserted', v_inserted,
    'updated', v_updated,
    'skipped', v_skipped,
    'pending', v_pending
  );
end;
$$;

revoke all on function public.accept_release_candidates(uuid, uuid[], text) from public, anon;
grant execute on function public.accept_release_candidates(uuid, uuid[], text) to authenticated;

create or replace function public.reject_release_candidates(
  p_run_id uuid,
  p_candidate_ids uuid[]
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_rejected integer := 0;
  v_pending integer := 0;
begin
  if coalesce(array_length(p_candidate_ids, 1), 0) = 0 then
    raise exception 'at least one candidate is required';
  end if;

  if not exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  ) then
    raise exception 'release admin access required';
  end if;

  update public.release_candidates
  set status = 'rejected', matched_release_id = null
  where run_id = p_run_id
    and id = any(p_candidate_ids)
    and status = 'pending';

  get diagnostics v_rejected = row_count;

  select count(*)::integer
  into v_pending
  from public.release_candidates
  where run_id = p_run_id
    and status = 'pending';

  update public.release_import_runs
  set
    status = case when v_pending = 0 then 'completed' else 'review' end,
    completed_at = case when v_pending = 0 then now() else null end,
    stats = jsonb_build_object(
      'pending', v_pending,
      'accepted', (
        select count(*)
        from public.release_candidates
        where run_id = p_run_id and status = 'accepted'
      ),
      'duplicates', (
        select count(*)
        from public.release_candidates
        where run_id = p_run_id and status = 'duplicate'
      ),
      'rejected', (
        select count(*)
        from public.release_candidates
        where run_id = p_run_id and status = 'rejected'
      )
    )
  where id = p_run_id;

  return jsonb_build_object(
    'rejected', v_rejected,
    'pending', v_pending
  );
end;
$$;

revoke all on function public.reject_release_candidates(uuid, uuid[]) from public, anon;
grant execute on function public.reject_release_candidates(uuid, uuid[]) to authenticated;

create or replace function public.rollback_release_import(p_run_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_change public.release_import_changes%rowtype;
  v_current public.releases%rowtype;
  v_restored integer := 0;
  v_skipped integer := 0;
  v_failed integer := 0;
begin
  if not exists (
    select 1
    from public.release_admins
    where user_id = (select auth.uid())
  ) then
    raise exception 'release admin access required';
  end if;

  perform 1
  from public.release_import_runs
  where id = p_run_id
  for update;

  if not found then
    raise exception 'release import run not found';
  end if;

  for v_change in
    select *
    from public.release_import_changes
    where run_id = p_run_id
      and rollback_status = 'pending'
    order by id desc
    for update
  loop
    begin
      select *
      into v_current
      from public.releases
      where identity_key = v_change.release_identity_key
      limit 1
      for update;

      if not found then
        update public.release_import_changes
        set
          rollback_status = 'skipped',
          rollback_message = 'Release no longer exists',
          rolled_back_at = now()
        where id = v_change.id;
        v_skipped := v_skipped + 1;
        continue;
      end if;

      if v_current.updated_at <> (v_change.after_snapshot ->> 'updated_at')::timestamptz then
        update public.release_import_changes
        set
          rollback_status = 'skipped',
          rollback_message = 'Release was edited after this import',
          rolled_back_at = now()
        where id = v_change.id;
        v_skipped := v_skipped + 1;
        continue;
      end if;

      if v_change.action = 'inserted' then
        delete from public.releases
        where id = v_current.id;
      else
        update public.releases
        set
          cover_url = v_change.before_snapshot ->> 'cover_url',
          storage_path = v_change.before_snapshot ->> 'storage_path',
          spotify_url = v_change.before_snapshot ->> 'spotify_url',
          spotify_pre_save_url = v_change.before_snapshot ->> 'spotify_pre_save_url',
          apple_music_url = v_change.before_snapshot ->> 'apple_music_url',
          youtube_url = v_change.before_snapshot ->> 'youtube_url',
          source_url = v_change.before_snapshot ->> 'source_url',
          description = v_change.before_snapshot ->> 'description',
          track_count = nullif(v_change.before_snapshot ->> 'track_count', '')::smallint,
          genres = coalesce(
            array(
              select jsonb_array_elements_text(v_change.before_snapshot -> 'genres')
            ),
            '{}'::text[]
          ),
          status = v_change.before_snapshot ->> 'status'
        where id = v_current.id;
      end if;

      update public.release_candidates
      set status = 'pending', matched_release_id = null
      where id = v_change.candidate_id;

      update public.release_import_changes
      set
        rollback_status = 'restored',
        rollback_message = null,
        rolled_back_at = now()
      where id = v_change.id;

      v_restored := v_restored + 1;
    exception
      when others then
        update public.release_import_changes
        set
          rollback_status = 'failed',
          rollback_message = left(sqlerrm, 500),
          rolled_back_at = now()
        where id = v_change.id;
        v_failed := v_failed + 1;
    end;
  end loop;

  update public.release_import_runs
  set
    status = case when v_failed = 0 and v_skipped = 0 then 'rolled_back' else 'review' end,
    completed_at = null
  where id = p_run_id;

  return jsonb_build_object(
    'restored', v_restored,
    'skipped', v_skipped,
    'failed', v_failed
  );
end;
$$;

revoke all on function public.rollback_release_import(uuid) from public, anon;
grant execute on function public.rollback_release_import(uuid) to authenticated;

comment on table public.release_import_runs is
  'One idempotent multi-source discovery and editorial review batch for a release Friday.';

comment on table public.release_candidates is
  'Private admin inbox containing normalized DE and US release candidates plus provenance and warnings.';

comment on table public.release_import_changes is
  'Audit log used to undo one inbox batch without overwriting later manual edits.';
